### ISSUE TITLE
Esri Enterprise/Portal Configuration for AWS Cognito

### ISSUE THREAD

**Issue by blairdgeo** [Esri/idp#3]
Hello,

I noticed that you have compiled documentation for using AWS Cognito as an Identity Store for AGOL.  Does such functionality and documentation exist for ArcGIS Enterprise?  Thank you.

Cheers,
Blair

**Comment by sha10152** [comment]
@blairdgeo Overall, the 'AWS Cognito' workflow for Enterprise is the same as ArcGIS Online (with some minor changes in the URLs/screenshots). These instructions can be followed until the doc is updated with Enterprise specific instructions. Please let us know if you find this helpful or if you have additional feedback. Thanks!

**Comment by simongis** [comment]
Can someone link to the original documentation for AGOL?

**Comment by sha10152** [comment]
> Can someone link to the original documentation for AGOL?

@simongis Please see doc here: https://github.com/Esri/idp/blob/main/Documentation/OpenID/AWS%20Cognito.md
